unit _udisplaycontext;

{$I icu.inc}

interface

{$IFNDEF U_HIDE_DRAFT_API}
type
  UDisplayContextType = (
    UDISPCTX_TYPE_DIALECT_HANDLING = 0,
    UDISPCTX_TYPE_CAPITALIZATION = 1
  );

  UDisplayContext = (
    UDISPCTX_STANDARD_NAMES = (Ord(UDISPCTX_TYPE_DIALECT_HANDLING) shl 8) + 0,
    UDISPCTX_DIALECT_NAMES = (Ord(UDISPCTX_TYPE_DIALECT_HANDLING) shl 8) + 1,
    UDISPCTX_CAPITALIZATION_NONE = (Ord(UDISPCTX_TYPE_CAPITALIZATION) shl 8) + 0,
    UDISPCTX_CAPITALIZATION_FOR_MIDDLE_OF_SENTENCE = (Ord(UDISPCTX_TYPE_CAPITALIZATION) shl 8) + 1,
    UDISPCTX_CAPITALIZATION_FOR_BEGINNING_OF_SENTENCE = (Ord(UDISPCTX_TYPE_CAPITALIZATION) shl 8) + 2,
    UDISPCTX_CAPITALIZATION_FOR_UI_LIST_OR_MENU = (Ord(UDISPCTX_TYPE_CAPITALIZATION) shl 8) + 3,
    UDISPCTX_CAPITALIZATION_FOR_STANDALONE = (Ord(UDISPCTX_TYPE_CAPITALIZATION) shl 8) + 4
  );
{$ENDIF ~U_HIDE_DRAFT_API}

implementation

end.
